server:
  port: 8082
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtestDB?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: # provide password here if necessary

  jpa:
    hibernate:
      ddl-auto: update # Change to 'update' if you want to update schema automatically
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: user

  security:
    jwt:
      secret-key: "dGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1zZWNyZXQta2V5LTI1Ng=="
      expiration: 86400000  # 24 hours in milliseconds

  mailing:
    frontend:
      activation-url: "http://localhost:4200/activate-account"

  mail:
    host: smtp.gmail.com
    port: 587
    username: yasminemzoughi4@gmail.com
    password: "byzs pdhq kyil whiu"
    admin:
      email: yasminemzoughi4@gmail.com
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
      connectiontimeout: 5000  # 5 seconds
      timeout: 5000           # 5 seconds
      writetimeout: 5000      # 5 seconds


springdoc:
  default-produces-type: application/json
  cloud:
    discovery:
      enabled: false  # Disable service discovery

eureka:
  client:
    enabled: false  # Disable Eureka client specifically
logging:
  level:
    org.springframework.web: DEBUG  # Logs HTTP request/response details
    org.springframework.validation: DEBUG  # Logs validation errors
    tn.esprit: DEBUG  # Logs from your application packages